#!/usr/bin/env bash
# adapters/kilocode/generate.sh — Renders shared context into .kilocode/rules/rules.md
# Usage: bash generate.sh <project_name>

set -euo pipefail

WORKSPACE="${HOME}/.ai-workspace"

source "${WORKSPACE}/adapters/_shared/render-context.sh"

generate_kilocode_rules() {
    local project="$1"
    local config="${WORKSPACE}/config.toml"

    local proj_path
    proj_path=$(grep -A5 "\\[projects\\.${project}\\]" "$config" | grep "^path" | head -1 | sed 's/.*= *"//' | sed 's/".*//')

    if [ -z "$proj_path" ] || [ ! -d "$proj_path" ]; then
        echo "Error: Project '${project}' not found: ${proj_path}" >&2
        return 1
    fi

    local kilo_dir="${proj_path}/.kilocode/rules"
    local mb_dir="${kilo_dir}/memory-bank"
    mkdir -p "$mb_dir"

    local rules_output="${kilo_dir}/rules.md"

    # ── Generate rules.md ──
    {
        echo "# KiloCode Rules — ${project}"
        echo ""
        echo "> Auto-generated by \`aiw sync\`. Do not edit directly."
        echo "> Source: ~/.ai-workspace/context/"
        echo ""

        # Extract conventions from shared context
        local ctx_file="${WORKSPACE}/context/CONTEXT.md"
        if [ -f "$ctx_file" ]; then
            # Pull out the "Global Conventions" and "Do NOT" sections
            sed -n '/^## Global Conventions/,/^## [^G]/p' "$ctx_file" | head -n -1
            echo ""
            sed -n '/^### Do NOT/,/^## /p' "$ctx_file" | head -n -1
        fi

        echo ""
        echo "## Context Management"
        echo ""
        echo "- Read \`memory-bank/context.md\` at the start of every session"
        echo "- Read \`memory-bank/brief.md\` for current goals and active work"
        echo "- Update brief via \`aiw brief\` — changes propagate on next \`aiw sync\`"
        echo "- Log significant decisions via \`aiw\` or edit decisions.md directly"
    } > "$rules_output"

    echo "Generated: ${rules_output}"

    # ── Sync memory bank files from shared context ──
    # context.md <- project CONTEXT.md
    local proj_ctx="${WORKSPACE}/context/projects/${project}/CONTEXT.md"
    if [ -f "$proj_ctx" ]; then
        cp "$proj_ctx" "${mb_dir}/context.md"
        echo "  Synced: memory-bank/context.md"
    fi

    # brief.md <- project brief.md
    local proj_brief="${WORKSPACE}/context/projects/${project}/brief.md"
    if [ -f "$proj_brief" ]; then
        cp "$proj_brief" "${mb_dir}/brief.md"
        echo "  Synced: memory-bank/brief.md"
    fi

    # history.md <- project decisions.md
    local proj_decisions="${WORKSPACE}/context/projects/${project}/decisions.md"
    if [ -f "$proj_decisions" ]; then
        cp "$proj_decisions" "${mb_dir}/history.md"
        echo "  Synced: memory-bank/history.md"
    fi
}

# ── Main ──
if [ $# -eq 0 ]; then
    echo "Generating KiloCode rules for all projects..."
    for project in $(list_projects); do
        generate_kilocode_rules "$project" || echo "  Skipped: ${project}"
    done
else
    generate_kilocode_rules "$1"
fi
