#!/usr/bin/env bash
# adapters/claude/generate.sh — Renders shared context into CLAUDE.md for a project
# Usage: bash generate.sh <project_name>
# Generates CLAUDE.md in the project root directory.

set -euo pipefail

WORKSPACE="${HOME}/.ai-workspace"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source shared context renderer
source "${WORKSPACE}/adapters/_shared/render-context.sh"

generate_claude_md() {
    local project="$1"
    local config="${WORKSPACE}/config.toml"

    # Resolve project path from config
    local proj_path
    proj_path=$(grep -A5 "\\[projects\\.${project}\\]" "$config" | grep "^path" | head -1 | sed 's/.*= *"//' | sed 's/".*//')

    if [ -z "$proj_path" ] || [ ! -d "$proj_path" ]; then
        echo "Error: Project '${project}' not found or path invalid: ${proj_path}" >&2
        return 1
    fi

    local output="${proj_path}/CLAUDE.md"

    # ── Generate CLAUDE.md ──
    {
        echo "# CLAUDE.md"
        echo ""
        echo "> Auto-generated by \`aiw sync\`. Do not edit directly."
        echo "> Source: ~/.ai-workspace/context/ — Edit there, then run \`aiw sync\`."
        echo ""

        # Render merged context
        render_context "$project"

        # ── Claude-specific additions ──
        echo ""
        echo "---"
        echo ""
        echo "## Development Commands"
        echo ""

        case "$project" in
            n8n-workflows)
                cat <<'COMMANDS'
### n8n Standalone (Quick Start)
```bash
docker run -it --rm --name n8n -p 5678:5678 -v ~/.n8n:/home/node/.n8n n8nio/n8n
```

### Workflow Import/Export
```bash
n8n export:workflow --id=<workflow-id> --output=workflow.json
n8n import:workflow --input=workflow.json
```

### n8n MCP Tool Pattern
```javascript
// 1. Discover → 2. Configure → 3. Validate → 4. Deploy
search_nodes({query: "http"})
get_node_essentials({nodeType: "nodes-base.httpRequest", includeExamples: true})
validate_workflow({workflow, options: {profile: "ai-friendly"}})
n8n_create_workflow({name, nodes, connections})
```
COMMANDS
                ;;
            n8n-devops-automation)
                cat <<'COMMANDS'
### Full Stack (Docker Compose)
```bash
cd setup/
docker-compose up -d                    # Start n8n + PostgreSQL + Redis + Grafana + Prometheus
docker-compose logs -f n8n              # Follow n8n logs
docker-compose down                     # Stop all services
```
Services: n8n (5678), PostgreSQL (5432), Redis (6379), Grafana (3000), Prometheus (9090)
COMMANDS
                ;;
            n8n-agentic-devops)
                cat <<'COMMANDS'
### Trigger Orchestrator
```bash
curl -X POST http://localhost:5678/webhook/start-orchestrator
```
COMMANDS
                ;;
            agentcore-devops-demo)
                cat <<'COMMANDS'
### Local Testing
```bash
pip install bedrock-agentcore strands-agents boto3
python test_local.py
```

### Deploy to AgentCore
```bash
agentcore configure
agentcore launch --agent infrastructure-health-agent
```
COMMANDS
                ;;
        esac
    } > "$output"

    echo "Generated: ${output}"
}

# ── Main ──
if [ $# -eq 0 ]; then
    echo "Generating CLAUDE.md for all projects..."
    for project in $(list_projects); do
        generate_claude_md "$project" || echo "  Skipped: ${project}"
    done
else
    generate_claude_md "$1"
fi
