#!/usr/bin/env bash
# adapters/codex/generate.sh — Renders shared context into AGENTS.md for a project
# Usage: bash generate.sh <project_name>

set -euo pipefail

WORKSPACE="${HOME}/.ai-workspace"

# Source shared context renderer
source "${WORKSPACE}/adapters/_shared/render-context.sh"

generate_agents_md() {
    local project="$1"
    local config="${WORKSPACE}/config.toml"

    local proj_path
    proj_path=$(grep -A5 "\\[projects\\.${project}\\]" "$config" | grep "^path" | head -1 | sed 's/.*= *"//' | sed 's/".*//')

    if [ -z "$proj_path" ] || [ ! -d "$proj_path" ]; then
        echo "Error: Project '${project}' not found: ${proj_path}" >&2
        return 1
    fi

    local output="${proj_path}/AGENTS.md"

    {
        echo "# AGENTS.md"
        echo ""
        echo "> Auto-generated by \`aiw sync\`. Do not edit directly."
        echo "> Source: ~/.ai-workspace/context/"
        echo ""
        echo "## Agent Directives"
        echo ""
        echo "You are working on the **${project}** project. Follow these conventions strictly."
        echo ""

        # Render the merged context
        render_context "$project"

        echo ""
        echo "---"
        echo ""
        echo "## Agent Behavior"
        echo ""
        echo "- Read the full context above before making changes"
        echo "- Follow the architecture patterns described"
        echo "- Do not hardcode environment-specific values"
        echo "- Test changes before committing"
        echo "- Log significant decisions"
    } > "$output"

    echo "Generated: ${output}"
}

# ── Main ──
if [ $# -eq 0 ]; then
    echo "Generating AGENTS.md for all projects..."
    for project in $(list_projects); do
        generate_agents_md "$project" || echo "  Skipped: ${project}"
    done
else
    generate_agents_md "$1"
fi
