#!/usr/bin/env bash
# adapters/cline/generate.sh — Renders shared context into .clinerules for a project
# Usage: bash generate.sh <project_name>

set -euo pipefail

WORKSPACE="${HOME}/.ai-workspace"

source "${WORKSPACE}/adapters/_shared/render-context.sh"

generate_clinerules() {
    local project="$1"
    local config="${WORKSPACE}/config.toml"

    local proj_path
    proj_path=$(grep -A5 "\\[projects\\.${project}\\]" "$config" | grep "^path" | head -1 | sed 's/.*= *"//' | sed 's/".*//')

    if [ -z "$proj_path" ] || [ ! -d "$proj_path" ]; then
        echo "Error: Project '${project}' not found: ${proj_path}" >&2
        return 1
    fi

    local output="${proj_path}/.clinerules"

    {
        echo "# Cline Rules — ${project}"
        echo ""
        echo "> Auto-generated by \`aiw sync\`. Do not edit directly."
        echo "> Source: ~/.ai-workspace/context/"
        echo ""

        # Render merged context (Cline reads .clinerules as plain markdown)
        render_context "$project"
    } > "$output"

    echo "Generated: ${output}"
}

# ── Main ──
if [ $# -eq 0 ]; then
    echo "Generating .clinerules for all projects..."
    for project in $(list_projects); do
        generate_clinerules "$project" || echo "  Skipped: ${project}"
    done
else
    generate_clinerules "$1"
fi
